labs/lab6_project/config/routes.rb
Rails.application.routes.draw do
  root "students#index"

  get "/students/onlyWomen", to:"students#onlyWomen" , :as => :onlyWomen
  get "/students/onlyFourthYear", to:"students#onlyFourthYear" , :as => :onlyFourthYear
  get "/students/older20", to:"students#older20" , :as => :older20

  resources :students

end

labs/lab6_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

labs/lab6_project/app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

labs/lab6_project/app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: true
  validates :surname, presence: true
  validates :middlename, presence: true
  validates :gender, presence: true
  validates :age, presence: true
  validates :year, presence: true
end

labs/lab6_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

labs/lab6_project/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

labs/lab6_project/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all.order(created_at: :desc)
  end

  def onlyWomen
    @students = Student.where("gender LIKE ?", '%female%').order(created_at: :desc)
  end

  def onlyFourthYear
    @students = Student.where("year == ?", 4).order(created_at: :desc)
  end

  def older20
    @students = Student.where("age >= ?", 20).order(created_at: :desc)
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to @student
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])

    if @student.update(student_params)
      redirect_to @student
    else
      render :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    redirect_to root_path
  end



  private
  def student_params
    params.require(:student).permit(:name, :surname, :middlename, :gender, :age, :year)
  end
end

labs/lab6_project/app/helpers/application_helper.rb
module ApplicationHelper
end

labs/lab6_project/app/helpers/articles_helper.rb
module ArticlesHelper
end

labs/lab6_project/app/helpers/students_helper.rb
module StudentsHelper
end

labs/lab6_project/app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

labs/lab6_project/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

labs/lab6_project/app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

labs/lab6_project/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

labs/lab6_project/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>

labs/lab6_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

labs/lab6_project/app/views/students/_footer.html.erb
<ul class="students-criteria">
  <li><%= link_to "Only women", onlyWomen_url %></li>
  <li><%= link_to "Only 4th year", onlyFourthYear_url %></li>
  <li><%= link_to "Older than 20", older20_url %></li>
</ul>

labs/lab6_project/app/views/students/_form.html.erb
<div class="wrap">
  <%= form_with model: @student do |form|  %>
    <div class="input-line">
      <%= form.label :name %>
      <%= form.text_field :name %>
      <% @student.errors.full_messages_for(:name).each do |message| %>
        <div class="error"> <%= message %></div>
      <% end %>
    </div>

    <div class="input-line">
      <%= form.label :surname %>
      <%= form.text_field :surname %>
      <% @student.errors.full_messages_for(:surname).each do |message| %>
        <div class="error"> <%= message %></div>
      <% end %>
    </div>

    <div class="input-line">
      <%= form.label :middlename %>
      <%= form.text_field :middlename %>
      <% @student.errors.full_messages_for(:middlename).each do |message| %>
        <div class="error"> <%= message %></div>
      <% end %>
    </div>

    <div class="input-line">
      <%= form.label :gender %>
      <%= form.text_field :gender %>
      <% @student.errors.full_messages_for(:gender).each do |message| %>
        <div class="error"> <%= message %></div>
      <% end %>
    </div>

    <div class="input-line">
      <%= form.label :age %>
      <%= form.text_field :age %>
      <% @student .errors.full_messages_for(:age).each do |message| %>
        <div class="error"><%= message %></div>
      <% end %>
    </div>

    <div class="input-line">
      <%= form.label :year %>
      <%= form.text_field :year %>
      <% @student .errors.full_messages_for(:year).each do |message| %>
        <div class="error"><%= message %></div>
      <% end %>
    </div>

    <div class="button">
      <%= form.submit %>
    </div>
  <% end %>
</div>

labs/lab6_project/app/views/students/_list.html.erb
<ul class="student-list">
  <li>
    <p>Name</p>
    <p>Surname</p>
    <p>Middlename</p>
    <p>Gender</p>
    <p>Age</p>
    <p>Year</p>
  </li>
  <% @students.each do |student| %>
    <li >
      <p><%= student.name %></p>
      <p><%= link_to student.surname , student %></p>
      <p><%= student.middlename %></p>
      <p><%= student.gender %></p>
      <p><%= student.age %> y.o.</p>
      <p><%= student.year %> course</p>
    </li>
  <% end %>
</ul>

labs/lab6_project/app/views/students/edit.html.erb
<h1>Edit Student Information</h1>

<%= render "form", article: @article %>

<%= render "footer"%>

labs/lab6_project/app/views/students/index.html.erb
<h1>All Students</h1>

<div class='button-new' style="justify-content: flex-end">
<%= link_to  new_student_path do%>
  <p>Add student</p>
<%end%>
</div>

<%= render "list", article: @students %>

<%= render "footer"%>

labs/lab6_project/app/views/students/new.html.erb
<h1>Add Student</h1>

<%= render "form", student: @student %>

<div class='button-new'>
  <%= link_to  "/students" do%>
    <p>Back</p>
  <%end%>
</div>

<%= render "footer"%>

labs/lab6_project/app/views/students/older20.html.erb
<h1>Only students older than 20</h1>

<%= render "list", article: @students %>

<div class='button-new'>
  <%= link_to  "/students" do%>
    <p>Back</p>
  <%end%>
</div>

<%= render "footer"%>

labs/lab6_project/app/views/students/onlyFourthYear.html.erb
<h1>Only students on their 4th year:</h1>

<%= render "list", article: @students %>

<div class='button-new'>
  <%= link_to  "/students" do%>
    <p>Back</p>
  <%end%>
</div>

<%= render "footer"%>

labs/lab6_project/app/views/students/onlyWomen.html.erb
<h1>Only women students:</h1>

<%= render "list", article: @students %>

<div class='button-new'>
  <%= link_to  "/students" do%>
    <p>Back</p>
  <%end%>
</div>

<%= render "footer"%>

labs/lab6_project/app/views/students/show.html.erb
<h1> Student: <%= @student.surname %> </h1>

<div class="wrap-info">
<ul class="student-info">
  <li>Name: <%= @student.name %></li>
  <li>Surname: <%= @student.surname %> </li>
  <li>Middlename: <%= @student.middlename %> </li>
  <li>Gender: <%= @student.gender %></li>
  <li>Age: <%= @student.age %> y.o. </li>
  <li>University year: <%= @student.year %> course</li>
</ul>
<div class='button-new delete'>
  <%= link_to  edit_student_path(@student) do%>
    <p>Edit</p>
  <%end%>
  <%= link_to  student_path(@student), method: :delete, data: { confirm: "Are you sure?" } do %>
    <p>Delete</p>
  <% end %>
</div>
</div>
<div class='button-new'>
  <%= link_to  "/students" do%>
    <p>Back</p>
  <%end%>
</div>

<%= render "footer"%>